# Generated by Django 3.2 on 2021-04-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managepics', '0002_alter_pic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='pic',
            field=models.ImageField(upload_to='images', verbose_name='Изображение'),
        ),
    ]
